name: Triggering Events

on:
  workflow_dispatch:
  push:
    branches:
      - "github-actions/*"
    
  pull_request: 
    types: 
      - opened
      - synchronize
      - reopened
    paths:
      - "app/*.txt"
      - "!./*.md"    
  
jobs:
  echo-event:
    runs-on: ubuntu-latest
    steps:
      - name: dump full event json
        run: |
          echo "=== $GITHUB_EVENT_NAME payload ==="
          cat "$GITHUB_EVENT_PATH"